### PR TITLE
chore(TDQ-19066) Upgrade 'jackson' to '2.11.3'

### PR DESCRIPTION
**Pull request by qiongli**
**What is the problem this Pull Request is trying to solve?**
 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Review by fhuaulme — COMMENTED** [review]
Is it possible to upgrade to a more recent version of Daikon rather than patching a very old maintenance branch?

**Review by fhuaulme — CHANGES_REQUESTED** [review]
Need answer on Daikon 4.1.0 upgrade first.

**Comment by qiongli** [comment]
> Is it possible to upgrade to a more recent version of Daikon rather than patching a very old maintenance branch?

**Comment by coheigea** [comment]
@qiongli What Daikon artifacts are you using in DQ? I am currently backporting security fixes in Daikon, and I am only backporting Daikon to 2.10.5, but for some artifacts I am also including 2.10.5.1 of the databind to fix the CVE.

**Review by coheigea — CHANGES_REQUESTED** [review]
I since updated 1.16 to use Jackson Databind 2.10.5.1. So if you still want 2.11.x, then you will need to update the PR.

**Comment by fhuaulme** [comment]
Checked with PR author: PR is no longer needed

**Pull request closed without merging**
