### PR TITLE
refactor(TDKN-140):moved migration interfaces to a migration package

### PR DESCRIPTION
**Pull request by sgandon**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
migration interface are mixed up with serialization classes

**What is the new behavior?**
migration interface are lcoated into their own migration folder.

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
all the migration interface used to migrate a Properties must now match the new package.
So they go from *org.talend.daikon.serialize* to *org.talend.daikon.serialize.migration*

**Other information**:
2 related PR will be created on the components repository and components-ee :
https://github.com/Talend/components/pull/515
https://github.com/Talend/components-ee/pull/77

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/59/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/59/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/100/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/100/)

**Comment by chmyga** [comment]
LGTM

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/6/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/6/)

**Pull request merged**
