### PR TITLE
feat(TPSVC-13666): add tag to the prometheus audit log counter

### PR DESCRIPTION
**Pull request by fuzmah**
**What is the problem this Pull Request is trying to solve?**
 This PR is complementary to #737. The goal is to add a tag to the counter in order to allow proper filtering in thanos 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TPSVC-13666
 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by fhuaulme** [comment]
Is this PR fully feature complete for the prometheus integration? Can you make sure it matches all your needs with a SNAPSHOT build for example?

**Comment by fuzmah** [comment]
That's what I will try to do. I just need this PR to not be merged until I'm sure which is why I added the WIP label

**Review by fhuaulme — CHANGES_REQUESTED** [review]
On hold pending validation.

**Comment by fuzmah** [comment]
@fhuaulme this one can be merged

**Review by fhuaulme — APPROVED** [review]

**Pull request merged**
