### PR TITLE
TDKN-337 - Update to SpringBoot 2.6.6

### PR DESCRIPTION
**Pull request by coheigea**
Update to SpringBoot 2.6.6

### CODE REVIEW

**Review by fabballe — APPROVED** [review]

**Review by sgandon — DISMISSED** [review]
LGTM

**Comment by coheigea** [comment]
@sgandon I fixed another critical Spring CVE in it, can you re-approve pls?

**Review by sgandon — DISMISSED** [review]
LGTM

**Comment by coheigea** [comment]
@sgandon The build failed with a test failure (passed for me locally). Should I merge or hold off?

**Comment by sgandon** [comment]
I'd rather find the reason for the build failure to avoid similar issue on master

**Comment by sgandon** [comment]
Can you have a look @coheigea  ?

**Comment by coheigea** [comment]
@sgandon Spring isn't even on the classpath in daikon-multitenant/multitenant-core. It looks like a flaky test to me. Is there a way of re-triggering the build?

**Pull request closed without merging**
