### PR TITLE
Kjwang/feat tup 20282 job signature and verification junit

### PR DESCRIPTION
**Pull request by kjwang-talend**
**What is the problem this Pull Request is trying to solve?**
 Improve the junit for CI plugin signer-maven-plugin
**What is the chosen solution to this problem?**
 1. Generate the certification by java code.
 2. Sign job by java code
 3. Verify the job by junit
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TUP-20989
 
**Please check if the Pull Request fulfills these requirements**
- [X] The PR commit message follows our [guidelines](../CONTRIBUTING.md)
- [X] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/6/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/6/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/7/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/7/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/8/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/8/)

**Comment by sgandon** [comment]
Why do you need this binary file
daikon-signature-verifier/src/test/resources/org/talend/daikon/signature/verify/unsigned.zip

?

**Comment by kjwang-talend** [comment]
> Why do you need this binary file
> daikon-signature-verifier/src/test/resources/org/talend/daikon/signature/verify/unsigned.zip
> 
> ?

unsigned.zip is a unsigned job that was generate by studio. In my test code will 
1. Sign this job first.
2. Check the signature use class **ZipVerifier** that to see whether **ZipVerifier** work as expect.

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/17/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/17/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/18/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/18/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/19/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/19/)

**Pull request merged**
