### PR TITLE
feat(TFD-6574): Add schemaUri in Message Header spec

### PR DESCRIPTION
**Pull request by bchen-talend**
**What is the problem this Pull Request is trying to solve?**
 Add SchemaUri in Message header spec, schemaUri point to a link to the schema that the message body adheres to. (e.g. http://org.talend.message/customer-logs/v1)
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/181/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/181/)

**Comment by sgandon** [comment]
Hi Chen bin, this is nice !
ciuld you add some unit tests please to make sure everything comforms to the specs ?

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/184/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/184/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/186/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/186/)

**Comment by fhuaulme** [comment]
@bchen-talend Is this PR still needed?

**Comment by fhuaulme** [comment]
Closing without merge this PR due to inactivity.

**Pull request closed without merging**
