### PR TITLE
fix(TBD-4268): Shade the commons-lang3 library in daikon.

### PR DESCRIPTION
**Pull request by RyanSkraba**
**Please check if the PR fulfills these requirements**

- [X] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Daikon depends on `commons-lang3`.

**What is the new behavior?**

This PR changes the behaviour of how it depends on `commons-lang3`.  This library causes an issue with other libraries in the Studio with other versions (notably Cloudera Hive components).  These other libraries can't be ugraded to the version used by daikon, and daikon requires the features of the version that it uses.

There should be no API changes.

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/324/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/324/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/336/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/336/)

**Comment by sgandon** [comment]
One question though, is is possible to have the shaded sources included in daikon sources  ?

**Comment by RyanSkraba** [comment]
Hello!  I've updated the bug.  This is probably an unsatisfactory solution, so please do not merge!

**Comment by RyanSkraba** [comment]
Quick - update: I think I found another solution.  I will close and delete this branch if it works out.

**Comment by sgandon** [comment]
@RyanSkraba So what is the verdict ? to close or not to close ?

**Comment by RyanSkraba** [comment]
Closing the pull request but keeping the branch as a temporary reference!

**Pull request closed without merging**
