### PR TITLE
fix(cumulative): Cumulative fixes for daikon

### PR DESCRIPTION
**Pull request by fhuaulme**
* Fix CVE for jackson version (2.9.4 -> 2.9.5)

**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDKN-204
 
**Please check if the Pull Request fulfills these requirements**
- [x] The PR commit message follows our [guidelines](../CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

### CODE REVIEW

**Comment by talend-vlesquere** [comment]
Hi, 
looking at the dependency tree, we can see that jackson-databind is still in 2.9.4 in daikon-spring-mongo
even if it's in the test scope
And what do you think about upgrading jackson-annotations and jackson-core to 2.9.5 also just for coherence ?

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/83/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/83/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/84/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/84/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/85/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/85/)

**Pull request merged**
