### PR TITLE
fix(TDKN-227): [Java 11 support] Need an update of commons-lang3 version

### PR DESCRIPTION
**Pull request by wwang-talend**
**What is the problem this Pull Request is trying to solve?**
 https://jira.talendforge.org/browse/TDKN-227

**What is the chosen solution to this problem?**
https://jira.talendforge.org/browse/TDKN-227
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDKN-227
 
**Please check if the Pull Request fulfills these requirements**
- [x] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request
 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/209/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/209/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/210/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/210/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/212/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/212/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/1/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/1/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/2/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/2/)

**Comment by wwang-talend** [comment]
seems the last failed is caused by the network issue
02:57:55 [main] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project dynamic-log: Failed to retrieve remote metadata org.talend.daikon:dynamic-log:1.2.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata org.talend.daikon:dynamic-log:1.2.0-SNAPSHOT/maven-metadata.xml from/to talend_nexus_deployment (https://nexus-smart-branch.datapwn.com/nexus/content/repositories/dev_branch_snapshots/branch_wwang-talend_tdkn-227): Failed to transfer file: https://nexus-smart-branch.datapwn.com/nexus/content/repositories/dev_branch_snapshots/branch_wwang-talend_tdkn-227/org/talend/daikon/dynamic-log/1.2.0-SNAPSHOT/maven-metadata.xml. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/3/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/3/)

**Pull request merged**
