### PR TITLE
TDKN-81: Support serialize/deserialize Properties to jsonschema 

### PR DESCRIPTION
**Pull request by bchen-talend**
moved from https://github.com/Talend/components/pull/246.

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/11/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/11/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/13/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/13/)

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/14/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/14/)

**Comment by bchen-talend** [comment]
build failure is due to a flaky test, not a change in this PR

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/31/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/31/)

**Pull request merged**
