### PR TITLE
fix(tds-1210): implement a kafka wrapper which ensure no messages are lost in case of kafka outage

### PR DESCRIPTION
**Pull request by afourmi**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [x] Docs have been added / updated (for bug fixes / features) ?
- [x] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** 
https://jira.talendforge.org/browse/TDS-1210

Currently, when kafka brokers are down, kafka messages are lost and can lead to data inconsistency in application using kafka

**What is the new behavior?**
Kafka messages are issued by a kafka wrapper, which store messages when kafka is down, and tries periodically to send them again. 

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/95/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/95/)

**Comment by afourmi** [comment]
I removed the "Merged build failed" flag because the last build c374a50 was a success but did not delete the flag

**Comment by sgandon** [comment]
Be carefull, there are 2 build for a PR, 
* one is a branch build, this will impact the branch and the PR status, 
* the second is a "merge to master" build which merges the branch to master and builds it, this will impact the label only.

**Comment by sgandon** [comment]
I'have trigger a merge build to have a proper status for the merge to master : https://ci-common.datapwn.com/job/daikon_pull-request_master/111/

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/112/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/112/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/154/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/154/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/156/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/156/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/158/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/158/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/159/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/159/)

**Comment by afourmi** [comment]
Rework has been done to improve code organisation and spring framework use
PRs have also been updated on Schema and TDS applications, which embed this library, to reflect these changes

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/160/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/160/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/161/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/161/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/54/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/54/)

**Pull request closed without merging**
