### PR TITLE
feat(TPSVC-1542): add new cusotm widget type: tabs, which is needed by react-talend-forms

### PR DESCRIPTION
**Pull request by Peiren**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/73/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/73/)

**Comment by glorieux** [comment]
@Peiren Please fill the description template content when publishing a pull request. It helps reviewers know what you're trying to accomplish.

**Comment by vjaouen** [comment]
IMHO tabs should be part of the component forms, not the component's properties. 
@Peiren To be sure I understand how you plan to enable tabs in form, can you provide an example ?

**Comment by sgandon** [comment]
@Peiren : What is the status of this PR ?

**Pull request closed without merging**
