### PR TITLE
[Version repository]

### PR DESCRIPTION
**Pull request by fhuaulme**
- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [x] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [x] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [x] Feature

**Does this PR introduce a breaking change?**

- [x] No

**Description**

[Common code]
* Add a common version repository to allow both data storage and event storage.
* Common storage and version operations (CRUD + log, reset, checkout).

[Service]
* Add a common REST service (for both local and remote access).
* Add a version-repository-parent for defining services dedicated to repository.

[Example]
* Add sample service for using version-repository-parent.

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/350/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/350/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/354/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/354/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/356/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/356/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/357/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/357/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/358/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/358/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/359/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/359/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/119/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/119/)

**Comment by build-talend-common** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/146/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/146/)

**Comment by fhuaulme** [comment]
Obsolete.

**Pull request closed without merging**
