### PR TITLE
chore(TDI-37213): remove di package from daikon

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [ ] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Daikon contains DI package with DI specific code

**What is the new behavior?**

DI packages moved to library in DI repository.
https://github.com/Talend/tdi-studio-se/tree/master/main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
https://jira.talendforge.org/browse/TDI-37213

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/110/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/110/)

**Comment by gonchar-ivan** [comment]
yes, sorry. I missed description.

This code was moved here:
https://github.com/Talend/tdi-studio-se/tree/master/main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/enforcer
https://github.com/Talend/tdi-studio-se/tree/master/main/plugins/org.talend.designer.components.libs/libs_src/talend-codegen-utils/src/main/java/org/talend/codegen/converter

correct library version is 0.20.0

It is already available on nexus:
https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceRelease/org/talend/libraries/talend-codegen-utils/0.20.0/

There was a PR to use new code in codegen:
https://github.com/Talend/tdi-studio-se/pull/1450/files
https://github.com/Talend/tdi-studio-se/pull/1447

Also I created a wiki page, which reminds that there are 2 places to switch talend-codegen-utils library version
https://wiki.talend.com/display/rd/Codegen

**Comment by sgandon** [comment]
fine, thank you. please merge whenever you are ready.

**Comment by francisu** [comment]
Congratulations on finally getting this done! It is very important work.

**Pull request merged**
