### PR TITLE
[Fix] Update S3 client (1.11.18 -> 1.11.83)

### PR DESCRIPTION
**Pull request by fhuaulme**
There is an issue in version 1.11.18 version of AWS clients. In the context of an EC2 instance, the SSL check for the AWS certificate was incorrectly handle, it was using **strict** host name validation where it should be using wildward validation.

In other words:

* "buket_name.s3.amazon.aws.com" does not validate certificate "*.s3.amazon.aws.com" in 1.11.18
* ... but does in 1.11.83.

Details:
* fix incorrect SSL policy (use of '*' in AWS issued SSL certificate).
* update code following minor API changes.
* remove usage of now deprecated class.

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/2/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/2/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/3/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/3/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/13/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/13/)

**Comment by fhuaulme** [comment]
No need to merge, issue was caused by incorrect configuration: bucket name must be "bucketname" and not "bucketname.s3.amazonaws.com".

**Pull request closed without merging**
