### PR TITLE
Bugfix/6.3/tcomp 333 enforcer improvement

### PR DESCRIPTION
**Pull request by gonchar-ivan**
**Please check if the PR fulfills these requirements**

- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format) ?
- [x] Tests for the changes have been added (for bug fixes / features) ?
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [x] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [x] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Current DiOutgoingSchemaEnforcer has performance bottlenecks and is not clear

**What is the new behavior?**

1. DiOutgoingSchemaEnforcer was splitted into 2 classes for dynamic and non-dynamic case
2. ByIndex/ByName logic was moved to separate IndexMapper classes
3. Added EnforcerCreator, which creates corresponding Enforcer (dynamic or not, with ByIndex or ByName field matching mode) according to arguments
4. Improved DiOutgoingSchemaEnforcer runtime performance. The main idea: do not compute something per record, which could be precomputed only once during initialization.

**Does this PR introduce a breaking change?**

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

Codegen plugin should be also edited to integrate this change

**Other information**:

Related to https://jira.talendforge.org/browse/TCOMP-333

**DO NOT MERGE UNTIL CODEGEN CHANGE IS MADE**

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [failure](https://ci-common.datapwn.com/job/daikon_pull-request_master/159/) [:x:](https://ci-common.datapwn.com/job/daikon_pull-request_master/159/)

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/170/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/170/)

**Comment by RyanSkraba** [comment]
Hello!  I can't compile and build this on my local machine because of a network outage, but I did a code review and this looks good to me (can be merged when TDI needs it!)

**Comment by gonchar-ivan** [comment]
I've pushed one more commit.
It contains little refactoring: runtime schema removed from constructors.
I've made design mistake. I thought DiOutgoingSchemaEnforcer is used only after Input components, so I decided set runtime schema in constructor. It is possible for Input components, because the first record may be retrieved from TCOMP Reader before loop upon records.
But it is not possible for Intermediate and Output (in case of Reject records) components.
So I had to swirch back to logic, in which runtime schema is retrieved from first incoming record.

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/180/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/180/)

**Comment by RyanSkraba** [comment]
Don't forget to make the necessary changes to the components library (there are test cases in Salesforce that use these classes)!

**Comment by gonchar-ivan** [comment]
Thanks!
It shouldn't be used in components.
It is planned to move di package from daikon to tdi-studio or tcommon.

**Pull request merged**
