### PR TITLE
fix(): Delete OperationTypes from header

### PR DESCRIPTION
**Pull request by fabballe**
**What is the problem this Pull Request is trying to solve?**

The field OperationTypes  was accidently merged on master. The goal of this PR is to remove it

**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [x] The PR commit message follows our [guidelines](../CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/12/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/12/)

**Comment by sgandon** [comment]
Thank Fabien for this PR. Will this change be backward compatible or is it a breaking change ?
I know you did not check the box on the PR description but I want to make sure this removal will not have any impact ?

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/15/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/15/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/31/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/31/)

**Pull request merged**
