### PR TITLE
Test pull reuqest

### PR DESCRIPTION
**Pull request by iwangtalend**

### CODE REVIEW

**Comment by build-talend** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/11/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/11/)

**Comment by iwangtalend** [comment]
Pull request test result: [failed]() [:x:]()

**Comment by iwangtalend** [comment]
Pull request test result: [success]() [:star:]()

**Comment by iwangtalend** [comment]
Pull request test result: [success]() [:star:]()

**Comment by iwangtalend** [comment]
Pull request test result: [success]() [:star:]()

**Comment by iwangtalend** [comment]
Pull request test result: [failed]() [:x:]()

**Comment by iwangtalend** [comment]
Pull request test result: [success]() [:star:]()

**Comment by sgandon** [comment]
bizarre le dernier set de label, le label *Merged build Failed* est rajouté puis retiré dans la même requete.

**Pull request closed without merging**
