### PR TITLE
[TDKN-23] Remove defaultValue from Property

### PR DESCRIPTION
**Pull request by bchen-talend**
[TDKN-23] Remove defaultValue from Property

### CODE REVIEW

**Comment by francisu** [comment]
Will you make a corresponding components request that goes with this?

**Comment by bchen-talend** [comment]
@francisu I checked salesforce component, no change needed, but may effect studio team maybe, need check

**Comment by francisu** [comment]
Almost certainly should be no impact with the studio, but good to check anyway. Let me know when you have checked and Seb or I will merge this.

**Comment by nrousseau** [comment]
Is it possible to set the old method of getDefault() / setDefault() as deprecated simply for now?
Seems much better rather than have a synchronized task

**Comment by sgandon** [comment]
if you deprecate them , they will go away eventually, then you'll have to check the studio anyway, so I'd say we do it now since the Studio is our only client right now.

**Comment by sgandon** [comment]
One comment though on the naming, since it is not the default value anymore because we will never be able to get it later, I would suggest to rename the parameters *initialValue* instead of *defaultValue*.

**Comment by bchen-talend** [comment]
Ok, @sgandon I will use initialValue as the name.
Do you think we can remove the following method directly?
```
@Deprecated
Property newInteger(String name, String defaultValue)
```

**Comment by sgandon** [comment]
nope this is a helper method that is useful, why would you add @Deprecated it ?

**Pull request merged**
