### PR TITLE
chore(TDKN-226): Mutualize Swagger for Spring applications

### PR DESCRIPTION
**Pull request by fhuaulme**
* add sample app in daikon-spring-examples.
* add daikon-spring-swagger-ui for a Talend custom UI (based on springfox's).
* add daikon-spring-swagger-configuration for common configuration.
* add bom to ease usage in application.

**What is the problem this Pull Request is trying to solve?**
 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDKN-226
 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by sgandon** [comment]
I believe we could benefit from some readme to explain things. 
It seems that swagger is quite simple to get but I suppose a readme would help.
Also what about the swagger security for those newly exposed endpoints ?

**Comment by fhuaulme** [comment]
Yes, this branch was created to give a proposal draft following dev team request. README files will come for sure

**Comment by fhuaulme** [comment]
... and good point about security 👍

**Comment by fhuaulme** [comment]
About security @sgandon : I checked with applications, none of them secure Swagger access at service level (they do at gateway level). And if they want to, this is a matter of a Spring Security configuration that would not be used.

**Pull request closed without merging**
