### PR TITLE
feat(TDC-2245): make BeanPredicateVisitor more extendable

### PR DESCRIPTION
**Pull request by pradasouvanlasy**
**What is the problem this Pull Request is trying to solve?**

A minimal implementation of the faceted search feature for TDC can be mostly based on the existing `BeanPredicateVisitor`. Only need to make few methods overridable or publicly visible while extending this visitor.
 
**What is the chosen solution to this problem?**

Few classes have been marked as `public` instead of the default "package protected" visibility. 
The `LanguageBinder` interface has been added in order to make few behaviours overridable.

There is no added logic whatsoever to the existing `BeanPredicateVisitor`.
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDC-2245
 
**Please check if the Pull Request fulfills these requirements**
- [X] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/31/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/31/)

**Comment by pradasouvanlasy** [comment]
@fhuaulme: still a work in progress but you can check https://github.com/Talend/dataset/blob/psouvanlasy/feat/TDC-2146_engineering_faceted/modules/dataset-refactoring/app/org/talend/dataset/tql/ExtendedBeanPredicateVisitor.scala

Basically, we need to override the default behaviour of the visitor on the following cases:
- it uses `String.valueOf` regardless of the actual value type. This is not suited for `scala.Option` objects for instance
- the `MethodAccessor` resolution logic does not work with `scala.Option`. Since we're evaluating scala case classes with the resulting predicate, we can simplify a bit the logic as well on our own visitor.

We can discuss this offline together if needed tomorrow

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/32/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/32/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/34/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/34/)

**Comment by build-talend-common** [comment]
Pull request test result: [success](https://ci-common.datapwn.com/job/daikon_pull-request_master/35/) [:star:](https://ci-common.datapwn.com/job/daikon_pull-request_master/35/)

**Pull request merged**
