### PR TITLE
chore(TFD-12613): add akka additional fields as labels

### PR DESCRIPTION
**Pull request by rdubois**
**What is the problem this Pull Request is trying to solve?**

Akka actors add additional fields to the MDC, which can be of interest for trousbleshooting issues.
 
**What is the chosen solution to this problem?**

Those additional fields are added to the logging events labels
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TFD-12613
 
**Please check if the Pull Request fulfills these requirements**
- [x] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

### CODE REVIEW

**Review by sgandon — APPROVED** [review]
LGTM but I'd like to also have the review from @jehervy  if that is ok with you.

**Comment by rdubois** [comment]
thanks @sgandon. Sure !

**Review by jehervy — APPROVED** [review]
LGTM as well 👌

**Comment by rdubois** [comment]
Thanks @sgandon and @jehervy

**Pull request merged**
